# Generated by Django 5.2.6 on 2025-09-12 10:21

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_gasnetwork_node_pipe_plc_plcalarm_sensor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationDataReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_start', models.IntegerField()),
                ('step_end', models.IntegerField()),
                ('influxdb_start_time', models.DateTimeField()),
                ('influxdb_end_time', models.DateTimeField()),
                ('data_points_count', models.IntegerField(default=0)),
                ('node_count', models.IntegerField(default=0)),
                ('pipe_count', models.IntegerField(default=0)),
                ('sensor_count', models.IntegerField(default=0)),
                ('plc_count', models.IntegerField(default=0)),
                ('avg_pressure', models.FloatField(blank=True, null=True)),
                ('max_pressure', models.FloatField(blank=True, null=True)),
                ('min_pressure', models.FloatField(blank=True, null=True)),
                ('avg_flow', models.FloatField(blank=True, null=True)),
                ('max_flow', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['simulation_run', 'step_start'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='simulationdata',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='simulationdata',
            name='run',
        ),
        migrations.AddIndex(
            model_name='plcalarm',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['plc', 'timestamp'], name='simulator_p_plc_id_e78ea6_btree'),
        ),
        migrations.AddIndex(
            model_name='plcalarm',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['severity', 'acknowledged'], name='simulator_p_severit_2d5204_btree'),
        ),
        migrations.AddIndex(
            model_name='plcalarm',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['timestamp'], name='simulator_p_timesta_543887_btree'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created'], name='simulator_r_created_519a9a_btree'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['network', 'status'], name='simulator_s_network_d6c314_btree'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created'], name='simulator_s_created_3453f4_btree'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['status'], name='simulator_s_status_efc200_btree'),
        ),
        migrations.AddIndex(
            model_name='valve',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['pipe'], name='simulator_v_pipe_id_3d37eb_btree'),
        ),
        migrations.AddIndex(
            model_name='valve',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['valve_type'], name='simulator_v_valve_t_a6fae5_btree'),
        ),
        migrations.AddIndex(
            model_name='valve',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_operational'], name='simulator_v_is_oper_3115ba_btree'),
        ),
        migrations.AddField(
            model_name='simulationdatareference',
            name='simulation_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_references', to='simulator.simulationrun'),
        ),
        migrations.DeleteModel(
            name='SimulationData',
        ),
        migrations.AddIndex(
            model_name='simulationdatareference',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['simulation_run', 'step_start'], name='simulator_s_simulat_c92269_btree'),
        ),
        migrations.AddIndex(
            model_name='simulationdatareference',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['influxdb_start_time', 'influxdb_end_time'], name='simulator_s_influxd_d514e3_btree'),
        ),
    ]
