# Generated by Django 5.2.6 on 2025-09-15 16:10

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_simulationdatareference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationTimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('measurement_type', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('simulation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries_data', to='simulator.simulationrun')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [
                    django.contrib.postgres.indexes.BTreeIndex(fields=['simulation_run', 'timestamp'], name='simulator_s_simulat_d8f766_btree'),
                    django.contrib.postgres.indexes.BTreeIndex(fields=['simulation_run', 'object_id'], name='simulator_s_simulat_3a9e33_btree'),
                    django.contrib.postgres.indexes.BTreeIndex(fields=['timestamp'], name='simulator_s_timesta_5c4b4d_btree'),
                    django.contrib.postgres.indexes.BTreeIndex(fields=['measurement_type'], name='simulator_s_measure_07c13a_btree'),
                ],
            },
        ),
        migrations.RemoveField(
            model_name='simulationdatareference',
            name='simulation_run',
        ),
        migrations.RemoveIndex(
            model_name='plcalarm',
            name='simulator_p_plc_id_e78ea6_btree',
        ),
        migrations.RemoveIndex(
            model_name='plcalarm',
            name='simulator_p_severit_2d5204_btree',
        ),
        migrations.RemoveIndex(
            model_name='plcalarm',
            name='simulator_p_timesta_543887_btree',
        ),
        migrations.RemoveIndex(
            model_name='run',
            name='simulator_r_created_519a9a_btree',
        ),
        migrations.RemoveIndex(
            model_name='simulationrun',
            name='simulator_s_network_d6c314_btree',
        ),
        migrations.RemoveIndex(
            model_name='simulationrun',
            name='simulator_s_created_3453f4_btree',
        ),
        migrations.RemoveIndex(
            model_name='simulationrun',
            name='simulator_s_status_efc200_btree',
        ),
        migrations.RemoveIndex(
            model_name='valve',
            name='simulator_v_pipe_id_3d37eb_btree',
        ),
        migrations.RemoveIndex(
            model_name='valve',
            name='simulator_v_valve_t_a6fae5_btree',
        ),
        migrations.RemoveIndex(
            model_name='valve',
            name='simulator_v_is_oper_3115ba_btree',
        ),
        migrations.AddIndex(
            model_name='plcalarm',
            index=models.Index(fields=['plc', 'timestamp'], name='simulator_p_plc_id_e78ea6_btree'),
        ),
        migrations.AddIndex(
            model_name='plcalarm',
            index=models.Index(fields=['severity', 'acknowledged'], name='simulator_p_severit_2d5204_btree'),
        ),
        migrations.AddIndex(
            model_name='plcalarm',
            index=models.Index(fields=['timestamp'], name='simulator_p_timesta_543887_btree'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['created'], name='simulator_r_created_519a9a_btree'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['network', 'status'], name='simulator_s_network_d6c314_btree'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['created'], name='simulator_s_created_3453f4_btree'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['status'], name='simulator_s_status_efc200_btree'),
        ),
        migrations.AddIndex(
            model_name='valve',
            index=models.Index(fields=['pipe'], name='simulator_v_pipe_id_3d37eb_btree'),
        ),
        migrations.AddIndex(
            model_name='valve',
            index=models.Index(fields=['valve_type'], name='simulator_v_valve_t_a6fae5_btree'),
        ),
        migrations.AddIndex(
            model_name='valve',
            index=models.Index(fields=['is_operational'], name='simulator_v_is_oper_3115ba_btree'),
        ),
        migrations.DeleteModel(
            name='SimulationDataReference',
        ),
    ]
