# Generated by Django 5.2.6 on 2025-10-10 09:09

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_simulationtimeseriesdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compressor_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('OFF', 'Off'), ('STARTING', 'Starting'), ('RUNNING', 'Running'), ('STOPPING', 'Stopping'), ('FAULT', 'Fault')], default='OFF', max_length=20)),
                ('speed', models.FloatField(default=0.0)),
                ('set_speed', models.FloatField(default=-1.0)),
                ('set_command', models.CharField(choices=[('AUTO', 'Auto'), ('ON', 'On'), ('OFF', 'Off')], default='AUTO', max_length=10)),
                ('max_speed', models.FloatField(default=15000.0)),
                ('max_pressure_ratio', models.FloatField(default=1.5)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='plcalarm',
            name='simulator_p_plc_id_e78ea6_btree',
        ),
        migrations.RemoveIndex(
            model_name='plcalarm',
            name='simulator_p_severit_2d5204_btree',
        ),
        migrations.RemoveIndex(
            model_name='plcalarm',
            name='simulator_p_timesta_543887_btree',
        ),
        migrations.RemoveIndex(
            model_name='run',
            name='simulator_r_created_519a9a_btree',
        ),
        migrations.RemoveIndex(
            model_name='simulationrun',
            name='simulator_s_network_d6c314_btree',
        ),
        migrations.RemoveIndex(
            model_name='simulationrun',
            name='simulator_s_created_3453f4_btree',
        ),
        migrations.RemoveIndex(
            model_name='simulationrun',
            name='simulator_s_status_efc200_btree',
        ),
        migrations.RemoveIndex(
            model_name='valve',
            name='simulator_v_pipe_id_3d37eb_btree',
        ),
        migrations.RemoveIndex(
            model_name='valve',
            name='simulator_v_valve_t_a6fae5_btree',
        ),
        migrations.RemoveIndex(
            model_name='valve',
            name='simulator_v_is_oper_3115ba_btree',
        ),
        migrations.RenameIndex(
            model_name='simulationtimeseriesdata',
            new_name='simulator_s_simulat_2bf502_btree',
            old_name='simulator_s_simulat_d8f766_btree',
        ),
        migrations.RenameIndex(
            model_name='simulationtimeseriesdata',
            new_name='simulator_s_simulat_a37506_btree',
            old_name='simulator_s_simulat_3a9e33_btree',
        ),
        migrations.RenameIndex(
            model_name='simulationtimeseriesdata',
            new_name='simulator_s_timesta_653e0f_btree',
            old_name='simulator_s_timesta_5c4b4d_btree',
        ),
        migrations.RenameIndex(
            model_name='simulationtimeseriesdata',
            new_name='simulator_s_measure_8a396c_btree',
            old_name='simulator_s_measure_07c13a_btree',
        ),
        migrations.AddField(
            model_name='node',
            name='set_flow',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='node',
            name='set_pressure',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='valve',
            name='set_position',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddIndex(
            model_name='plcalarm',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['plc', 'timestamp'], name='simulator_p_plc_id_e78ea6_btree'),
        ),
        migrations.AddIndex(
            model_name='plcalarm',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['severity', 'acknowledged'], name='simulator_p_severit_2d5204_btree'),
        ),
        migrations.AddIndex(
            model_name='plcalarm',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['timestamp'], name='simulator_p_timesta_543887_btree'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created'], name='simulator_r_created_519a9a_btree'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['network', 'status'], name='simulator_s_network_d6c314_btree'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created'], name='simulator_s_created_3453f4_btree'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['status'], name='simulator_s_status_efc200_btree'),
        ),
        migrations.AddIndex(
            model_name='valve',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['pipe'], name='simulator_v_pipe_id_3d37eb_btree'),
        ),
        migrations.AddIndex(
            model_name='valve',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['valve_type'], name='simulator_v_valve_t_a6fae5_btree'),
        ),
        migrations.AddIndex(
            model_name='valve',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_operational'], name='simulator_v_is_oper_3115ba_btree'),
        ),
        migrations.AddField(
            model_name='compressor',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compressors', to='simulator.node'),
        ),
        migrations.AddField(
            model_name='compressor',
            name='plc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulator.plc'),
        ),
    ]
